#!/usr/bin/env bash
# This script transfers a file from a local machine to the remote sever

source_path=$1
remote_host=$2
remote_user=$3
identity_file=$4

if [[ $# -eq 4 ]]
then
	scp -i $identity_file -o StrictHostKeyChecking=no $source_path  $remote_user@$remote_host:~/
# Disabled the StrictHotKeys option
else
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
 

