#!/usr/bin/env bash
# install nginx on our server and add a redirection to it

sudo apt update -y
sudo apt-get install nginx -y

echo "Hello World!" | sudo tee  /var/www/html/index.html
sudo sed -i '/server_name _/a rewrite ^/redirect_me https://www.youtube.com/watch?v=XT0nNuSDW8w&t=22s permanent;' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > var/www/html/404.html
sudo sed -i '/server_name _;/a eror_page 404 /404.html;\n location = /404.html {root /var/www/html;\n internal;}' /etc/nginx/sites-available/default
sudo service nginx restart
