#!/usr/bin/env bash
# configure nginx to have a custom header which will be the hostname

sudo apt-get update -y
sudo apt-get install nginx -y


sudo mkdir -p /var/www/html

# change permissions to allow us to easily create files in this directory
sudo chmod -R 755 /var/www

echo "Hello World" | sudo tee /var/www/html/index.html

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# code to configure redirect for a single page(/redirect_me) and add header to display hostname
string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# code to configure redirect for 404 error page
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
