#!/usr/bin/env bash
# Loop through 10 times and print bad luck on 4th interation
# print good luck on 8th interation
# print Best school for other iterations

count=0
while (("$count < 10"))
do
	if [ "$count" -eq 3 ]
	then
		echo "bad luck"
	elif [ "$count" -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi

	((count++))
done