#!/usr/bin/env bash
# display time hour from 0 to 9 and minutes from 1 to 59

hour=0
while (("$hour" <= 12))
do
	echo "Hour: $hour"
	minutes=1
	while (("$minutes" <= 59))
	do
		echo "$minutes"
		((minutes++))
	done
	((hour++))
done
